name: Deploy jackdriscoll.io 

on:
  push:
    branches:
      - deployment

env:
  AWS_REGION: us-east-1  # Replace with your AWS region
  ECR_REPOSITORY_URI: 339712977374.dkr.ecr.us-east-1.amazonaws.com/jackdriscoll.io 
  LIGHTSAIL_INSTANCE_NAME: jackdriscoll.io  

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2


      - name: Build, tag, and push image to Amazon ECR
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t ${{ env.ECR_REPOSITORY_URI }}:$IMAGE_TAG .
          docker push ${{ env.ECR_REPOSITORY_URI }}:$IMAGE_TAG
    
      - name: Print success message
        run: echo "Successfully built and pushed image to ECR"


      - name: Deploy to Lightsail
        env:
          IMAGE_TAG: ${{ github.sha }}
          PRIVATE_KEY: ${{ secrets.LIGHTSAIL_SSH_KEY }}
        run: |
          echo "$PRIVATE_KEY" > lightsail_key.pem
          chmod 600 lightsail_key.pem
          ssh -i lightsail_key.pem -o StrictHostKeyChecking=no ec2-user@${{ secrets.LIGHTSAIL_IP_ADDRESS }} << EOF
            aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin ${{ env.ECR_REPOSITORY_URI }}
            docker pull ${{ env.ECR_REPOSITORY_URI }}:$IMAGE_TAG
            docker stop jackdriscoll_io || true
            docker rm jackdriscoll_io || true
            docker run -d --name jackdriscoll_io -p 80:80 -p 443:443 -v /etc/letsencrypt:/etc/letsencrypt -v /home/ec2-user/nginx-logs:/var/log/nginx/ ${{ env.ECR_REPOSITORY_URI }}:$IMAGE_TAG
            exit
          EOF

      - name: Print success message
        run: echo "Successfully deployed to Lightsail"